# spring.application.name=backend
# spring.datasource.url=jdbc:mysql://root:WNquhPrQkBzRQTqaspTXjjkahcfmVIpZ@turntable.proxy.rlwy.net:11287/railway
# spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# jwt.secret=${JWT_SECRET}
# # jwt.expiration=${JWT_EXPIRATION}

# spring.jackson.serialization.indent-output=false

spring.profiles.active=dev

spring.application.name=backend
#railwayDB
# spring.datasource.url=jdbc:postgresql://tramway.proxy.rlwy.net:13068/railway?currentSchema=public
# spring.datasource.url=jdbc:postgresql://tramway.proxy.rlwy.net:13068/railway?currentSchema=public&stringtype=unspecified
# spring.datasource.url=jdbc:mysql://shuttle.proxy.rlwy.net:42865/railway?useSSL=false&serverTimezone=UTC
spring.datasource.url=${DB_URL}




# spring.datasource.username=postgres
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# spring.datasource.password=ZZeTDHhWpQVnMDuQwrIwfmHUIKQWoUSu
# spring.datasource.driver-class-name=org.postgresql.Driver

#localDB
# spring.datasource.url=jdbc:sqlserver://localhost\\SQLEXPRESS:1433;databaseName=stayvida;TrustServerCertificate=true

# spring.datasource.username=admin
# spring.datasource.password=admin
# spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver

jwt.secret=${JWT_SECRET}
CORS=${ALLOWED_CORS_ORIGINS}
google.client.id=${google_client_id}
google.client.secret=${google_client_secret}

# Google OAuth configuration
spring.security.oauth2.client.registration.google.client-id=${google_client_id}
spring.security.oauth2.client.registration.google.client-secret=${google_client_secret}
# google.redirect.uri=http://localhost:8080/login/oauth2/code/google
google.redirect.uri=https://sv-website-backend-1.onrender.com/login/oauth2/code/google


# Max file size
spring.servlet.multipart.max-file-size=20MB
# Max request size (total request, includes form data + file)
spring.servlet.multipart.max-request-size=20MB
# spring.datasource.hikari.data-source-properties.serverTimezone=Asia/Kolkata
# application.properties
#API Keys
api.key=${API_KEY}
# Email Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=service.stayvida@gmail.com
spring.mail.password=${email_password}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
spring.servlet.multipart.enabled=true






# === Supabase configuration ===

supabase.url=${SUPABASE_URL}
supabase.key=${SUPABASE_ANON_KEY}
supabase.auth.url = ${SUPABASE_AUTH_URL}
supabase.jwt.secret = ${SUPABASE_JWT_SECRET}
# supabase.url=https://vpdeibjihiottdvuqsms.supabase.co
# supabase.key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZwZGVpYmppaGlvdHRkdnVxc21zIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE4NzkxMjcsImV4cCI6MjA3NzQ1NTEyN30.T8Yx1cTjmxsQlmTiYKzxLR_cNIjI5H9wuJMD_gwKjy4

# supabase.auth.url=https://vpdeibjihiottdvuqsms.supabase.co/auth/v1
# supabase.jwt.secret=Bxj5b4hNppkzU0grHOrPZU5YdKPIxwfxEtBF4vQMFnKI0chZYvOj5d4psJDuwTwVn3KWZCzoEzh6Da2pDCQ+uQ==




# 📁 File storage location
app.upload.dir=C:/uploaded_images

# 🌐 Public base URL for serving images
app.base.url=http://localhost:8080/image/

cloudinary.urlPrefix=https://res.cloudinary.com/damm4pumh/image/upload/stayvida/

# Razorpay
razorpay.key.id=${razerpay_key_id}
razorpay.key.secret=${razerpay_key_secret}
